channels:
- conda-forge
dependencies:
- python=3.9.0
- pip<=23.0
- pip:
  - mlflow<3,>=2.3
  - cffi==1.15.1
  - cloudpickle==2.2.1
  - defusedxml==0.7.1
  - ipython==8.12.0
  - numpy==1.23.5
  - packaging==23.1
  - pandas==2.0.1
  - psutil==5.9.5
  - scikit-image==0.20.0
  - scikit-learn==1.2.2
  - scipy==1.9.1
  - tqdm==4.65.0
name: mlflow-env
